name: weixin

on:
  workflow_dispatch:  # 允许手动触发工作流
  schedule:           # 定时触发工作流
    - cron: '0 38 7,9,13,15 * * *'  # 每天的7点、9点、13点、15点的第38分钟触发
    - cron: '0 35 22 * * *'         # 每天的22点的第35分钟触发
    - cron: '0 34 7 * * *'          # 每天的7点的第34分钟触发

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.12
      - name: Set timezone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run weixin script
        run: |
          python3 main.py
