name: weixin

on:
  workflow_dispatch:
  schedule:
    - cron: '34 23 * * *'
    - cron: '38 23 * * *'
    - cron: '38 1 * * *'
    - cron: '38 5 * * *'
    - cron: '38 7 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.12
      - name: Set timezone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run weixin script
        run: |
          python3 main.py
